### ISSUE TITLE
Crash using version 1.1.5

### ISSUE THREAD

**Issue by jakeyks** [screret/screenJS#1]
When I load the game using version 1.1.5 of this mod, I receive a crash with the following message:
`java.lang.RuntimeException: Illegal private member with @SubscribeEvent annotation`
This doesn't happen with older versions of the mod. I have attached latest.log and the crash report.
[latest.log](https://github.com/screret/screenJS/files/11190374/latest.log)
[crash-2023-04-10_13.10.16-fml.txt](https://github.com/screret/screenJS/files/11190375/crash-2023-04-10_13.10.16-fml.txt)

**Comment by BogusAlgorithm** [comment]
Can confirm same issue `[modloading-worker-0/ERROR]: Failed to register automatic subscribers. ModID: screenjs, class screret.screenjs.ScreenJS
java.lang.RuntimeException: Illegal private member with @SubscribeEvent annotation`
